services:
  server:
    image: ghcr.io/ionaru/fruiz/server:${FRUIZ_GIT_REVISION:-latest}
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    environment:
      - FRUIZ_SECURE_COOKIES
      - FRUIZ_RP_ID
      - FRUIZ_DEBUG
    ports:
      - "${FRUIZ_PORT:-8000}:8000"
    volumes:
      - ${FRUIZ_DATA_VOLUME:-data}:/app/data
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - deno task db:sync && exec deno task start

volumes:
  data:
